sudo: false
language: ruby
script: script/ci.sh
cache: bundler
rvm:
  - 1.9.3
  - '2.0'
  - '2.1'
  - '2.2'
  - jruby-19mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-19mode
